---
name: 'build docker image on develop'

on:
  push:
    branches:
      - develop

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Docker build
        run: |
          docker buildx build \
            --platform  linux/amd64,linux/arm/v7 \
            --tag ghcr.io/r0perice/mediapart-slack-bot:${GITHUB_REF##*/} \
            .
