name: Build Docker Image and Push to Registry

on:
  push:
    tags:
       - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    ## LOGIN
    - name: docker login
      env:
       DOCKER_USER: ${{ secrets.DOCKER_USER }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_PASSWORD
   ## BUILD IMAGE
    - name: docker build
      run: docker build -t docker.pkg.github.com/r0perice/mediapart-discord-bot/mediapart-discord-bot:${GITHUB_REF##*/} -f Dockerfile .
    ## PUSH IMAGE TO REGISTRY
    - name: docker push
      run: docker push docker.pkg.github.com/r0perice/mediapart-discord-bot/mediapart-discord-bot:${GITHUB_REF##*/}