---
name: 'build docker image and push to registry'

on:
  push:
    tags:
       - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Docker build
        run: |
          docker buildx build \
            --platform  linux/amd64,linux/arm/v7 \
            --tag ghcr.io/r0perice/mediapart-slack-bot:${GITHUB_REF##*/} \
            .
      
      - name: Docker login
        env:
         DOCKER_USER: ${{ secrets.DOCKER_USER }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login ghcr.io -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Docker push
        run: |
          docker buildx build \
            --platform  linux/amd64,linux/arm/v7 \
            --tag ghcr.io/r0perice/mediapart-slack-bot:${GITHUB_REF##*/} \
            . \
            --push  
